#!/usr/bin/env bash
# Display information about a domain name.

display_info () {
	DOMAIN=$1
	SUB_DOMAIN=$2
	DOMAIN_NAME=$SUB_DOMAIN.$DOMAIN
	INFO=$(dig $DOMAIN_NAME \
		| grep -A1 "ANSWER SECTION" \
		| tail -1)
	RECORD_TYPE=$(echo $INFO | awk -F" " '{print $4}')
	DESTINATION=$(echo $INFO | awk -F" " '{print $5}')

	echo "The subdomain $SUB_DOMAIN is a $RECORD_TYPE record and points to $DESTINATION"
}

DOMAIN=$1

if [[ $# -eq 2 ]]
then
	SUB_DOMAIN=$2
	display_info $DOMAIN $SUB_DOMAIN
else
	for SUB_DOMAIN in "www" "lb-01" "web-01" "web-02"
	do
		display_info $DOMAIN $SUB_DOMAIN
	done
fi
