#!/usr/bin/env bash
# Copy a file to remote server

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
PRIVATE_KEY=$4

if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no \
		-i ${PRIVATE_KEY} \
		${FILE_PATH} \
		${USERNAME}@${SERVER_IP}:
fi
