#!/usr/bin/env bash

# Set up Nginx on a server with a custom 404 page

# Install required packages
apt-get -y update
apt-get -y install nginx

# Set domain name
DOMAIN_NAME="thekamel.tech"

# Configure Nginx
{
    echo "server {"
    echo "	listen 80 default_server;"
    echo "	listen [::]:80 default_server;"
    echo "	server_name $DOMAIN_NAME;"
    echo '	root /var/www/html;'
    echo '	error_page 404 /404.html;'
    echo '	location /redirect_me {'
    echo '		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;'
    echo '	}'
    echo "	location = /404.html {"
    echo "		internal;"
    echo "	}"
    echo '}'
} > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

# Display domain name
echo "$DOMAIN_NAME"

