#!/usr/bin/env bash

# Configure Nginx redirection

# Set redirection URL
REDIRECT_URL="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Configure Nginx redirection
{
    echo "server {"
    echo "	listen 80 default_server;"
    echo "	listen [::]:80 default_server;"
    echo '	server_name "";'
    echo '	root /var/www/html;'
    echo "	location /redirect_me {"
    echo "		return 301 $REDIRECT_URL;"
    echo "	}"
    echo '}'
} > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

