#!/usr/bin/env bash
# Set up Nginx on a server

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

{
	echo "server {"
	echo "	listen 80 default_server;"
	echo "	listen [::]:80 default_server;"
	echo '	server_name "";'
	echo '	root /var/www/html;'
	echo '	error_page 404 /404.html;'
	echo '	location /redirect_me {'
	echo '		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;'
	echo '	}'
	echo '}'
} > /etc/nginx/sites-available/default

service nginx restart
