#!/usr/bin/env bash

# Configure Nginx custom 404 page

# Install required packages
apt-get -y update
apt-get -y install nginx

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx for custom 404 page
{
    echo "server {"
    echo "	listen 80 default_server;"
    echo "	listen [::]:80 default_server;"
    echo '	server_name "";'
    echo '	root /var/www/html;'
    echo '	error_page 404 /404.html;'
    echo "	location = /404.html {"
    echo "		internal;"
    echo "	}"
    echo '}'
} > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

