#!/usr/bin/env bash
# configures a brand new Ubuntu machine

apt update && apt upgrade -y
apt install nginx -y
{
	echo "server {"
	echo "	listen 80;"
	echo "	listen [::]:80;"
	echo '	server_name _ "";'
	echo '	add_header X-Served-By "$hostname";'
	echo "}"
} > /etc/nginx/sites-available/default
service nginx restart;
