#!/usr/bin/env bash
# configuring a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo service haproxy start

echo 'frontend theproxy
	bind *:80
	default_backend my_backend_servers

backend my_backend_servers
	balance roundrobin
	server 415843-web-01 18.234.107.161:80
        server 415843-web-02 54.172.57.77:80' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy reload
