#!/usr/bin/env bash
# Runs series of commands
trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit 0" SIGTERM
trap "echo ''Y U no love me?!" SIGINT
trap "rm -rf /var/run/myscript.pid; exit 0" SIGQUIT
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
