#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS.
i=1
n=$(wc -l /etc/passwd | cut -d " " -f1)
while [ $i -le "$n" ]
do
	line=$(head -n $i /etc/passwd | tail -n 1)

	username=$(cut -d: -f1 <(echo "$line"))
	gid=$(cut -d: -f4 <(echo "$line"))
	dir=$(cut -d: -f6 <(echo "$line"))
	shell=$(cut -d: -f7 <(echo "$line"))
	uid=$(cut -d: -f3 <(echo "$line"))
	password=$(cut -d: -f2 <(echo "$line"))
	info=$(cut -d: -f5 <(echo "$line"))

	echo -n "The user $username is part of the $gid gang, "
	echo -n "lives in $dir and rides $shell"
	echo -n ". $uid"
	echo -n "'s place is protected by the passcode $password"
	echo ", more info about the user here: $info"

	i=$((i + 1))
done
